### ISSUE TITLE
decode problem on strawberry 5.26

### ISSUE THREAD

**Issue by LorenzoTa** [choroba/pm-cb#15]
hello,

In my new machine with win10 I freshly installed Strawberry Perl (64-bit) Portable 5.26.0.2-64bit
plus a bounch of modules needed by your program:
`Perl 5.026000  MCE::Hobo 1.831  Parallel::ForkManager 1.19  Encode 2.92`

then I got no messages displayed in the chatbox but inly timestamps of private messages and the following error:

`
d:\SCRIPTS>perl pmchatTk09.pl -b blue -f gold -a red -mce
Prototype mismatch: sub main::decode: none vs ($$;$) at D:/ulisse/perl5.26.64bit/perl/lib/Exporter.pm line 66, <__ANONIO__> line 16.
 at D:/ulisse/perl5.26.64bit/perl/site/lib/Tk.pm line 22.
Use of uninitialized value $message in concatenation (.) or string at pmchatTk09.pl line 298, <__ANONIO__> line 2.
Use of uninitialized value $message in concatenation (.) or string at pmchatTk09.pl line 298, <__ANONIO__> line 19.
Use of uninitialized value $msg in substitution (s///) at pmchatTk09.pl line 306, <__ANONIO__> line 29.
Use of uninitialized value $msg in concatenation (.) or string at pmchatTk09.pl line 320, <__ANONIO__> line 29.
Use of uninitialized value $msg in substitution (s///) at pmchatTk09.pl line 306, <__ANONIO__> line 30.
Use of uninitialized value $msg in concatenation (.) or string at pmchatTk09.pl line 320, <__ANONIO__> line 30.
Use of uninitialized value $msg in substitution (s///) at pmchatTk09.pl line 306, <__ANONIO__> line 31.
Use of uninitialized value $msg in concatenation (.) or string at pmchatTk09.pl line 320, <__ANONIO__> line 31.
Use of uninitialized value $msg in substitution (s///) at pmchatTk09.pl line 306, <__ANONIO__> line 32.

..etc etc
`

Renaming your sub decode in _decode the problem disappeared

thanks
Discipulus

**Comment by choroba** [comment]
Can you try this change?

```
diff --git a/pm-cb-g b/pm-cb-g
index 1ea8186..cef2a83 100755
--- a/pm-cb-g
+++ b/pm-cb-g
@@ -195,7 +195,7 @@ sub gui {
     my $last_date = q();
 
     require Tk;
-    'Tk'->import;
+    # 'Tk'->import;
 
     require Tk::Dialog;
     require Tk::ROText;
@@ -270,7 +270,7 @@ sub gui {
 
     $mw->after(1, sub { login_dialog($mw); $write->focus; });
 
-    MainLoop();
+    Tk::MainLoop();
 }
```

**Comment by LorenzoTa** [comment]
I have applied the above patch and everything seems running smooth.
so the guilty was Tk->import? in effect why import at all? thanks anyway:

Discipulus

**Comment by choroba** [comment]
import made it possible to use MainLoop without Tk::. Evidently not worth it.
