### ISSUE TITLE
bareword found at line 63 and full path needed for Proc::Background on win32

### ISSUE THREAD

**Issue by LorenzoTa** [choroba/pm-cb#16]
hello, with Latest commit e6900b6  I have errors:

1)with `sub { $_[0]->list(threads::running)}` I get:
`Bareword "threads::running" not allowed while "strict subs" in use at pmchatTk10.pl line 48.
BEGIN not safe after errors--compilation aborted at pmchatTk10.pl line 63.`

No errors quoting it  `sub { $_[0]->list('threads::running')}` so this seems easy

2) Proc::Background alwys needs absolute path for executables on windows
`perl -MProc::Background -we "Proc::Background->new('start', 'www.perlmonks.org') or die qq($^E)"
-e: cannot find absolute location of start`

2a) unfortunately 'start' it's not even a command! it does not exists a start.exe in the filesystem.
It is a so called 'internal command' internal to cmd.exe See [https://ss64.com/nt/syntax-internal.html](url)

2b) playing with 'cmd.exe /k start ..' is a pain and probably adead path

2c) Assuming chrome as default browser, you need full path anyway:
`perl -MProc::Background -we "Proc::Background->new('chrome',  'www.perlmonks.org') or die qq($^E)"
-e: cannot find absolute location of chrome`

with full path is ok, but you need to specify 'http:\\www....' :

`perl -MProc::Background -we "Proc::Background->new('C:\Program Files (x86)\Google\Chrome\Application\chrome',  'http:\\www.perlmonks.org') or die qq($^E)"`

2d) So, if the 'start' trick is useful while in cmd.exe is not usable outside it: to get default browser on windows you must access the registry at `HKEY_CURRENT_USER\Software\Clients\StartMenuInternet\(Default) ` is not difficult. if you want I can write a BEGIN block for win32 users or you can simply `die "Win32 users MUST specify the browser used for link with full path"`

PS `perl pmchatTk10.pl -b blue -f gold -a red -mce -B "C:\Program Files (x86)\Google\Chrome\Application\chrome"` runs fine

thanks
Discipulus

**Comment by LorenzoTa** [comment]
update for 2d):
the above key seems no longer valid for win10 at least: another one _can_ be useful:

`reg query HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\Shell\Associations\URLAssociations\http\UserChoice

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\Shell\Associations\URLAssociations\http\UserChoice
    Hash    REG_SZ    YPgZRS+UyTs=
    ProgId    REG_SZ    ChromeHTML`

**Comment by choroba** [comment]
The bareword was fixed in e95edc21692a694406cc7f98b42773fc64252a8f. It's a constant, so quoting it works just by chance.

I reworked the URL opening in 18550967b7d68ea979e547c667daf5daa158b0a9. Let's see how it works.
