### ISSUE TITLE
Font setting not working on Ubuntu

### ISSUE THREAD

**Issue by 1nickt** [choroba/pm-cb#28]
I changed the font to Arial which I have installed in my system, but the app still uses the default which is a serif font of some kind.

This is on Ubuntu Xenia.

**Comment by LorenzoTa** [comment]
this happens changing fonts using the Options control or even with the command line -font_name Arial?

**Comment by 1nickt** [comment]
This happens changing the font with the Options.

It also happens using `-F Arial`.

In both cases the options dialog shows that the font has been set to Arial, but it does not change the display.

However, changing the font size does work.

**Comment by choroba** [comment]
Works for me on OpenSUSE. Are you sure Arial is installed? Does it work in a simple Tk application?

**Comment by 1nickt** [comment]
I'm a relatively new user of Ubuntu desktop, but Arial shows in the Font Viewer applet, and I  can use it in desktop applications.

But It does not seem to work in Tk. In fact, no font I tried, monospace or not, was displayed correctly.

Here's my test script. 
```
use strict; use warnings;
use Tk;

my $mw = new MainWindow;
my $code_font = $mw->fontCreate('arial', -family => 'Arial', -size => 12);
$mw->Label(-text => 'Hello World!', -font => 'arial')->pack;
$mw->Button(-text => 'Quit', -command => sub{exit} )->pack;
MainLoop;

__END__
```
I'm not sure what the problem is, but looks like it's not `pm-cb-g`.

**Comment by 1nickt** [comment]
I tested using the vendor perl and vendor Perl libs on my Ubuntu Xenia system and the fonts displayed as expected.

Closing this as it is clearly not a pm-cb-g issue.
