### ISSUE TITLE
bad event type or keysym "Page_Up"

### ISSUE THREAD

**Issue by LorenzoTa** [choroba/pm-cb#30]
hello, tryng the latest version 52d2105 I got:
`bad event type or keysym "Page_Up" at D:/ulisse/perl5.26.64bit/perl/site/lib/Tk/Derived.pm line 469.
Perl exited with active threads:
        2 running and unjoined
        0 finished and unjoined
        0 running and detached`

**Comment by choroba** [comment]
Weird, it works for me. Can you replace `Page_Up` with `Prior` and `Page_Down` with `Next` and check it works?

**Comment by LorenzoTa** [comment]
it works, thanks. iirc on windows is not first time I encountered bit different key definitions

update: see [http://www.tcl.tk/man/tcl8.4/TkCmd/keysyms.htm](url)

also in the future you can use:
`#!/usr/local/bin/perl -w 

use English; 
use Tk; 
use strict; 
my $mw = MainWindow->new; 
$mw->Label(-text => 'Type a character to see its keysym.')->grid; 
$mw->Button(qw/-text Quit -command/ => \&exit)->grid; 
$mw->bind('<Key>' => \&print_keysym); 
MainLoop; 
sub print_keysym { 

    my $e = $mw->XEvent;    # get reference to X11 event structure 
    my($keysym_text, $keysym_decimal) = ($e->K, $e->N); 
    my($X, $Y, $x, $y) = ($e->X, $e->Y, $e->x, $e->y); 
    print "Character = $keysym_decimal, keysym = $keysym_text" . 
        " at abs=($X,$Y), rel=($x,$y).\n"; 
}
__END__
Character = 65365, keysym = Prior at abs=(866,373), rel=(624,108).
Character = 65366, keysym = Next at abs=(866,373), rel=(624,108).`
sligthly modified from what i found [http://computer-programming-forum.com/33-perl/0a710813ccda8879.htm](url)
