### ISSUE TITLE
Right-click menu on links/URL's

### ISSUE THREAD

**Issue by Tux** [choroba/pm-cb#34]
Can I please have a right-click menu on links/URL's with at least the command "Copy URL" (or "Copy link address"), so I can open it in an application of choice.

**Comment by Tux** [comment]
```
diff --git a/lib/PM/CB/GUI.pm b/lib/PM/CB/GUI.pm
index bf2ff2c..2f5a206 100644
--- a/lib/PM/CB/GUI.pm
+++ b/lib/PM/CB/GUI.pm
@@ -3,6 +3,7 @@ package PM::CB::GUI;
 use 5.18.2;
 use warnings;

+use Clipboard;
 use constant {
     TITLE        => 'PM::CB::G',
     PUBLIC       => 0,
@@ -450,6 +451,8 @@ sub show {
                        sub { $self->{balloon}->detach($text) });
         $text->tagBind($tag, '<Button-1>',
                        sub { browse($self->url($url)) });
+        $text->tagBind($tag, '<Button-3>',
+                       sub { Clipboard->copy($self->url($url)) });
     }
     $text->see('end');
 }
```

**Comment by choroba** [comment]
`Button-3` is already bound to the context menu, it seems your change adds the new behaviour while keeping the old one. What about binding it to `Control-Button-1`?

**Comment by Tux** [comment]
Fine with me. Whatever :)

**Comment by Tux** [comment]
abcffc566236374d87f1aa48c6c9ff9edd209b61 works fine. Maybe make it configurable. I think I'd prefer Button-2 after some thought, but thanks! Merge!

**Comment by Tux** [comment]
See https://github.com/Tux/pm-cb/commit/a9eb2c74a7f41788764fbcc3db59945ac0ee977a

**Comment by choroba** [comment]
Configurable event added in 90850b5d7755611be6a3d99431c5d1ec41b8f282.
