### ISSUE TITLE
Shift-Insert does not paste on input window

### ISSUE THREAD

**Issue by Tux** [choroba/pm-cb#35]
Middle-button paste does work, but being a keyboard junk I want Shift-Insert to also work. I tried this:
```
diff --git a/lib/PM/CB/GUI.pm b/lib/PM/CB/GUI.pm
index bf2ff2c..3ae6340 100644
--- a/lib/PM/CB/GUI.pm
+++ b/lib/PM/CB/GUI.pm
@@ -3,6 +3,7 @@ package PM::CB::GUI;
 use 5.18.2;
 use warnings;

+use Clipboard;
 use constant {
     TITLE        => 'PM::CB::G',
     PUBLIC       => 0,
@@ -70,6 +71,11 @@ sub gui {
         -foreground => $self->{fg_color},
         -wrap       => 'word',
     )->pack(-fill => 'x');
+    $write->bind("<Shift-Insert>", sub {
+        say "FOOO!";
+        my $txt = Clipboard->paste;
+       say $txt;
+       $txt and $write->insert('end', $txt) });

     my $button_f = $mw->Frame->pack;
     my $send_b = $button_f->Button(-text => 'Send',
```
but it prints `FOOO!` and than hangs, so maybe the is some conflict deep down somewhere. (I also used `'insert'` instead of `'end'`, but it proves to hang before the `say $txt;`

**Comment by choroba** [comment]
I tried to fix it by

        my $paste = 'Clipboard'->paste;
        if (length $paste) {
            if (length $write->Contents) {
                $write->insert('insert', $paste);
            } else {
                $write->Contents($paste);
            }
        }

but it doesn't help either. This seems like a bug in Tk. Interestingly, `Ctrl-V` works normally.

**Comment by choroba** [comment]
Hm, it seems [Clipboard](http://p3rl.org/Clipboard) doesn't play well with [Tk](http://p3rl.org/Tk). But Tk already has clipboard methods, so trying with them...

**Comment by Tux** [comment]
ce78da4de5462bfb7d155c99b76e54fa9f320741 works fine. Happy, Merge!
