### ISSUE TITLE
Feature request: save history in file

### ISSUE THREAD

**Issue by Tux** [choroba/pm-cb#36]
Like hexchat: save the window history in a file (e.g. ~/.pm-cb/logs/pm.log = easy to grep) and reload last n lines (configurable in ~/.pm-cb/config, default 50, see https://github.com/choroba/pm-cb/issues/37) on restart.
Now that #cbstream is out of order, there is no log in my hexchat logs to grep or scrollback in. Having pm-cb-g always open would get me that back

**Comment by choroba** [comment]
Almost implemented in 19f4c330993d0703860db1ab2cb24171b40616b9. It reloads the whole last session on startup.
