### ISSUE TITLE
pm-cb/pm-cb-g GPLv2 license information not provided within github repository

### ISSUE THREAD

**Issue by Cosmic37** [choroba/pm-cb#60]
Hi choroba, Thanks again for our discussion at Perl Monks website today. From what you said I believe the pm-cb-g code is free software according to the GPLv2 license. Please could you add an appropriate statement confirming this on the code/github repository?
Many thanks, Cosmic37

**Comment by choroba** [comment]
Fixed by a517378a67ee3413be25f894269f569d4443eac2
